### ISSUE TITLE
front end scaffolding installations throw a npm error

### ISSUE THREAD

**Issue by apolopena** [apolopena/gitpod-laravel8-starter#76]
### Describe the bug
If React, Vue or Bootstrap is installed ala 'laravel/ui' an `npm` error is thrown

From the npm error log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/gitpod/.nvm/versions/node/v14.16.0/bin/node',
1 verbose cli   '/home/gitpod/.nvm/versions/node/v14.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'development'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
5 info lifecycle @~predevelopment: @
6 info lifecycle @~development: @
7 verbose lifecycle @~development: unsafe-perm in lifecycle true
8 verbose lifecycle @~development: PATH: /home/gitpod/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/workspace/gitpod-laravel8-starter/node_modules/.bin:/home/gitpod/.nvm/versions/node/v14.16.0/bin:/tmp/yarn--1616783743790-0.4004209842427078:/workspace/gitpod-laravel8-starter/node_modules/.bin:/home/gitpod/.config/yarn/link/node_modules/.bin:/home/gitpod/.yarn/bin:/home/gitpod/.nvm/versions/node/v14.16.0/libexec/lib/node_modules/npm/bin/node-gyp-bin:/home/gitpod/.nvm/versions/node/v14.16.0/lib/node_modules/npm/bin/node-gyp-bin:/home/gitpod/.nvm/versions/node/v14.16.0/bin/node_modules/npm/bin/node-gyp-bin:/home/gitpod/.sdkman/candidates/maven/current/bin:/home/gitpod/.sdkman/candidates/java/current/bin:/home/gitpod/.sdkman/candidates/gradle/current/bin:/home/gitpod/.rvm/gems/ruby-2.6.6/bin:/home/gitpod/.rvm/gems/ruby-2.6.6@global/bin:/home/gitpod/.rvm/rubies/ruby-2.6.6/bin:/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/home/gitpod/.pyenv/shims:/workspace/.cargo/bin:/workspace/.pip-modules/bin:/workspace/.rvm/bin:/ide/bin:/home/gitpod/.pyenv/bin:/home/gitpod/.pyenv/shims:/workspace/go/bin:/home/gitpod/go/bin:/home/gitpod/go-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:/home/gitpod/.nvm/versions/node/v14.16.0/bin:/home/gitpod/.cargo/bin:/home/gitpod/.rvm/bin
9 verbose lifecycle @~development: CWD: /workspace/gitpod-laravel8-starter
10 silly lifecycle @~development: Args: [ '-c', 'mix' ]
11 silly lifecycle @~development: Returned: code: 1  signal: null
12 info lifecycle @~development: Failed to exec development script
13 verbose stack Error: @ development: `mix`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/gitpod/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/gitpod/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid @
15 verbose cwd /workspace/gitpod-laravel8-starter
16 verbose Linux 5.4.0-1024-gcp
17 verbose argv "/home/gitpod/.nvm/versions/node/v14.16.0/bin/node" "/home/gitpod/.nvm/versions/node/v14.16.0/bin/npm" "run" "development"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error @ development: `mix`
22 error Exit status 1
23 error Failed at the @ development script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Steps to reproduce

1. Fork or brach this repo
2. Change the install value of _either_ react, vue or bootstrap to 1, push that change to the remote repo
3. Create a new workspace from the fork or branch of this repo.

### Expected behavior
No `npm` errors should occur during the initialization process.

### Additional information
It is hard to tell if the npm error breaks anything but at a minimum it can make the user loose confidence that they workspace was properly initialized.
After alot of testing an update of `npm` from `6.14.11` to `7.7.5` made the error go away so this will be part of the fix.

**Comment by apolopena** [comment]
Depends on https://github.com/apolopena/gitpod-laravel8-starter/issues/77
